### DISCUSSION TITLE
Solution to add footer to 404 page

### DISCUSSION THREAD

**Discussion by Steve0Greatness** [theforumhelpers/theforumhelpers.github.io#266] [Ideas]
I think that I've come up with a way to add the footer to the 404 page.
element(only on the 404 page):
```html
<footer id="footer" class="nanPage"></footer>
```
css:
```css
footer.nanPage {
   position: absolute;
   bottom: 0;
   width: 100%;
}
```
of course, this is just how I think it could be implemented in, so it's probably not the best.
