### ISSUE TITLE
Feature Request: Increase padding for navbar links 

### ISSUE THREAD

**Issue by BarelySmooth** [theforumhelpers/theforumhelpers.github.io#189]
**Is your feature request related to a problem?**
Yes. There isn't enough left and right padding between links in the navigation bar. Currently, it is only 5px.

**Describe alternatives you've considered**
Increase the padding to about 15px. Anywhere between 10px and 15px would be fine.

**Additional context**
Currently, it looks like this:
![image](https://user-images.githubusercontent.com/83728060/118501425-c15c4280-b739-11eb-98d0-a2acc8e3c15f.png)

I tested it out with increased padding:
![image](https://user-images.githubusercontent.com/83728060/118504488-9cb59a00-b73c-11eb-9a53-7a517b20927e.png)

Another thing to consider is the max-width at which the site will switch to mobile view. 
```css
@media only screen and (max-width: 1100px) {
   ...
}
```
Here, ```max-width``` has to be increased. Changing it to ```1220px``` worked for me (with 15px padding).

**Comment by gosoccerboy5** [comment]
One-line fix
from
```css
.nav_button {
    /* ... */
    padding: 25px 5px 25px 5px;
    /* ... */
}
```
to
```css
.nav_button {
    /* ... */
    padding: 25px 10px 25px 10px;
    /* ... */
}
```
